CREATE TABLE "MONTHLY_WORKSPACES" (
  "user_id" uuid NOT NULL,
  "period" varchar(7) NOT NULL,
  "workspace_id" uuid NOT NULL,
  "created_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "MONTHLY_WORKSPACES_pkey" PRIMARY KEY ("user_id", "period")
);
CREATE UNIQUE INDEX "MONTHLY_WORKSPACES_workspace_id_key" ON "MONTHLY_WORKSPACES"("workspace_id");
CREATE INDEX "MONTHLY_WORKSPACES_period_idx" ON "MONTHLY_WORKSPACES"("period");
ALTER TABLE "MONTHLY_WORKSPACES" ADD CONSTRAINT "MONTHLY_WORKSPACES_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "USERS"("id") ON DELETE RESTRICT;
ALTER TABLE "MONTHLY_WORKSPACES" ADD CONSTRAINT "MONTHLY_WORKSPACES_workspace_id_fkey" FOREIGN KEY ("workspace_id") REFERENCES "WORKSPACES"("id") ON DELETE RESTRICT;
