CREATE TYPE "WORKSPACE_INVITATION_STATUS" AS ENUM ('pending', 'accepted', 'rejected', 'cancelled');

CREATE TABLE "WORKSPACE_INVITATION" (
  "id" uuid PRIMARY KEY,
  "workspace_id" uuid NOT NULL,
  "invitee_id" uuid NOT NULL,
  "inviter_id" uuid NOT NULL,
  "role_id" uuid NOT NULL,
  "status" "WORKSPACE_INVITATION_STATUS" NOT NULL DEFAULT 'pending',
  "created_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "responded_at" timestamptz
);
ALTER TABLE "WORKSPACE_INVITATION" ADD CONSTRAINT "WORKSPACE_INVITATION_workspace_id_fkey" FOREIGN KEY ("workspace_id") REFERENCES "WORKSPACES"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "WORKSPACE_INVITATION" ADD CONSTRAINT "WORKSPACE_INVITATION_invitee_id_fkey" FOREIGN KEY ("invitee_id") REFERENCES "USERS"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "WORKSPACE_INVITATION" ADD CONSTRAINT "WORKSPACE_INVITATION_inviter_id_fkey" FOREIGN KEY ("inviter_id") REFERENCES "USERS"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "WORKSPACE_INVITATION" ADD CONSTRAINT "WORKSPACE_INVITATION_role_id_fkey" FOREIGN KEY ("role_id") REFERENCES "ROLE"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
CREATE INDEX "WORKSPACE_INVITATION_invitee_id_status_idx" ON "WORKSPACE_INVITATION"("invitee_id", "status");
CREATE INDEX "WORKSPACE_INVITATION_workspace_id_status_idx" ON "WORKSPACE_INVITATION"("workspace_id", "status");
