services:
  migrate:
    build:
      context: .
      target: migrate
    env_file: .env.docker
    restart: "no"
    extra_hosts:
      - "host.docker.internal:host-gateway"

  app:
    build:
      context: .
      target: runner
    env_file: .env.docker
    ports:
      - "3000:3000"
    depends_on:
      migrate:
        condition: service_completed_successfully
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"
