import type { CreateCategoryInput, UpdateCategoryInput } from "@/domain";
import { AppError } from "@/lib/errors";
import { prisma } from "@/lib/prisma";

export const GLOBAL_CATEGORY_CONFIRMATION_PASSWORD = "oggykhongcochinhkien";
export function assertGlobalCategoryConfirmation(password: string) { if (password !== GLOBAL_CATEGORY_CONFIRMATION_PASSWORD) throw new AppError("FORBIDDEN", "Mật khẩu xác nhận category chung không đúng."); }
async function parent(parentId: string | undefined, type: "income" | "expense", categoryId?: string) { if (!parentId) return; if (parentId === categoryId) throw new AppError("VALIDATION_ERROR", "Danh mục không thể là cha của chính nó."); const item = await prisma.category.findFirst({ where: { id: parentId, workspaceId: null, status: "active", deletedAt: null } }); if (!item) throw new AppError("FORBIDDEN", "Danh mục cha chung không hợp lệ."); if (item.type !== type) throw new AppError("VALIDATION_ERROR", "Danh mục con phải cùng loại Thu hoặc Chi."); let ancestorId = item.parentId; while (ancestorId) { if (ancestorId === categoryId) throw new AppError("VALIDATION_ERROR", "Không thể tạo vòng lặp danh mục."); const ancestor = await prisma.category.findUnique({ where: { id: ancestorId }, select: { parentId: true } }); ancestorId = ancestor?.parentId ?? null; } }
export async function createGlobalCategory(userId: string, password: string, input: CreateCategoryInput) { assertGlobalCategoryConfirmation(password); await parent(input.parentId, input.type); const user = await prisma.user.findFirst({ where: { id: userId, status: "active", deletedAt: null } }); if (!user) throw new AppError("AUTHENTICATION_REQUIRED", "Cần đăng nhập."); if (await prisma.category.findFirst({ where: { workspaceId: null, code: input.code, deletedAt: null } })) throw new AppError("CONFLICT", "Mã category chung đã tồn tại."); return prisma.category.create({ data: { ...input, workspaceId: null } }); }
export async function updateGlobalCategory(userId: string, password: string, input: UpdateCategoryInput) { assertGlobalCategoryConfirmation(password); const item = await prisma.category.findFirst({ where: { id: input.categoryId, workspaceId: null, deletedAt: null } }); if (!item) throw new AppError("NOT_FOUND", "Category chung không tồn tại."); await parent(input.parentId, input.type, item.id); const duplicate = await prisma.category.findFirst({ where: { workspaceId: null, code: input.code, id: { not: item.id }, deletedAt: null } }); if (duplicate) throw new AppError("CONFLICT", "Mã category chung đã tồn tại."); return prisma.category.update({ where: { id: item.id }, data: { name: input.name, code: input.code, color: input.color, type: input.type, icon: input.icon, parentId: input.parentId ?? null, sortOrder: input.sortOrder } }); }
export async function setGlobalCategoryStatus(userId: string, password: string, categoryId: string, status: "active" | "deactive") { assertGlobalCategoryConfirmation(password); const item = await prisma.category.findFirst({ where: { id: categoryId, workspaceId: null, deletedAt: null } }); if (!item) throw new AppError("NOT_FOUND", "Category chung không tồn tại."); if (status === "deactive" && await prisma.category.count({ where: { workspaceId: null, parentId: item.id, status: "active", deletedAt: null } })) throw new AppError("VALIDATION_ERROR", "Hãy xử lý category con đang hoạt động trước."); return prisma.category.update({ where: { id: item.id }, data: { status } }); }
