ALTER TYPE "TRANSACTION_PURPOSE" ADD VALUE IF NOT EXISTS 'credit_card_installment_fee';

CREATE TYPE "FELIX_INSTALLMENT_STATUS" AS ENUM ('pending', 'active', 'completed');
CREATE TYPE "FELIX_STATEMENT_STATUS" AS ENUM ('issued', 'paid');

ALTER TABLE "CREDIT_CARD_PROFILE"
  ADD COLUMN IF NOT EXISTS "statement_closing_day" INTEGER,
  ADD COLUMN IF NOT EXISTS "payment_due_day" INTEGER;

UPDATE "CREDIT_CARD_PROFILE"
SET "statement_closing_day" = 25, "payment_due_day" = 10
WHERE "statement_closing_day" IS NULL OR "payment_due_day" IS NULL;

ALTER TABLE "CREDIT_CARD_PROFILE"
  ALTER COLUMN "statement_closing_day" SET NOT NULL,
  ALTER COLUMN "payment_due_day" SET NOT NULL,
  ADD CONSTRAINT "CREDIT_CARD_PROFILE_statement_closing_day_check" CHECK ("statement_closing_day" BETWEEN 1 AND 31),
  ADD CONSTRAINT "CREDIT_CARD_PROFILE_payment_due_day_check" CHECK ("payment_due_day" BETWEEN 1 AND 31);

ALTER TABLE "TRANSACTION" ADD COLUMN IF NOT EXISTS "billing_statement_id" UUID;

CREATE TABLE "CREDIT_CARD_EQUAL_INSTALLMENT_PLAN" (
  "id" UUID NOT NULL,
  "workspace_id" UUID NOT NULL,
  "card_wallet_id" UUID NOT NULL,
  "transaction_id" UUID NOT NULL,
  "fee_transaction_id" UUID,
  "created_by_member_id" UUID NOT NULL,
  "term_count" INTEGER NOT NULL,
  "fee_amount" DECIMAL(20,4) NOT NULL DEFAULT 0,
  "effective_date" DATE NOT NULL,
  "status" "FELIX_INSTALLMENT_STATUS" NOT NULL DEFAULT 'pending',
  "activated_at" TIMESTAMPTZ(6),
  "completed_at" TIMESTAMPTZ(6),
  "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" TIMESTAMPTZ(6) NOT NULL,
  CONSTRAINT "CREDIT_CARD_EQUAL_INSTALLMENT_PLAN_pkey" PRIMARY KEY ("id"),
  CONSTRAINT "CREDIT_CARD_EQUAL_INSTALLMENT_PLAN_term_count_check" CHECK ("term_count" IN (3, 6, 9, 12, 18, 24)),
  CONSTRAINT "CREDIT_CARD_EQUAL_INSTALLMENT_PLAN_fee_amount_check" CHECK ("fee_amount" >= 0)
);

CREATE TABLE "CREDIT_CARD_INSTALLMENT" (
  "id" UUID NOT NULL,
  "plan_id" UUID NOT NULL,
  "installment_no" INTEGER NOT NULL,
  "statement_date" DATE NOT NULL,
  "due_date" DATE NOT NULL,
  "principal_amount" DECIMAL(20,4) NOT NULL,
  "fee_amount" DECIMAL(20,4) NOT NULL DEFAULT 0,
  "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "CREDIT_CARD_INSTALLMENT_pkey" PRIMARY KEY ("id"),
  CONSTRAINT "CREDIT_CARD_INSTALLMENT_number_check" CHECK ("installment_no" > 0),
  CONSTRAINT "CREDIT_CARD_INSTALLMENT_amount_check" CHECK ("principal_amount" > 0 AND "fee_amount" >= 0)
);

CREATE TABLE "CREDIT_CARD_BILLING_STATEMENT" (
  "id" UUID NOT NULL,
  "workspace_id" UUID NOT NULL,
  "card_wallet_id" UUID NOT NULL,
  "cycle_start_date" DATE NOT NULL,
  "cycle_end_date" DATE NOT NULL,
  "due_date" DATE NOT NULL,
  "total_amount" DECIMAL(20,4) NOT NULL,
  "status" "FELIX_STATEMENT_STATUS" NOT NULL DEFAULT 'issued',
  "paid_at" TIMESTAMPTZ(6),
  "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "CREDIT_CARD_BILLING_STATEMENT_pkey" PRIMARY KEY ("id"),
  CONSTRAINT "CREDIT_CARD_BILLING_STATEMENT_dates_check" CHECK ("cycle_start_date" <= "cycle_end_date" AND "due_date" > "cycle_end_date")
);

CREATE TABLE "CREDIT_CARD_BILLING_STATEMENT_ITEM" (
  "id" UUID NOT NULL,
  "statement_id" UUID NOT NULL,
  "obligation_entry_id" UUID NOT NULL,
  "installment_id" UUID,
  "funding_wallet_id" UUID NOT NULL,
  "amount" DECIMAL(20,4) NOT NULL,
  "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "CREDIT_CARD_BILLING_STATEMENT_ITEM_pkey" PRIMARY KEY ("id"),
  CONSTRAINT "CREDIT_CARD_BILLING_STATEMENT_ITEM_amount_check" CHECK ("amount" <> 0)
);

CREATE UNIQUE INDEX "CREDIT_CARD_EQUAL_INSTALLMENT_PLAN_transaction_id_key" ON "CREDIT_CARD_EQUAL_INSTALLMENT_PLAN"("transaction_id");
CREATE UNIQUE INDEX "CREDIT_CARD_EQUAL_INSTALLMENT_PLAN_fee_transaction_id_key" ON "CREDIT_CARD_EQUAL_INSTALLMENT_PLAN"("fee_transaction_id");
CREATE INDEX "CREDIT_CARD_EQUAL_INSTALLMENT_PLAN_workspace_id_status_idx" ON "CREDIT_CARD_EQUAL_INSTALLMENT_PLAN"("workspace_id", "status");
CREATE INDEX "CREDIT_CARD_EQUAL_INSTALLMENT_PLAN_card_wallet_id_status_idx" ON "CREDIT_CARD_EQUAL_INSTALLMENT_PLAN"("card_wallet_id", "status");
CREATE UNIQUE INDEX "CREDIT_CARD_INSTALLMENT_plan_id_installment_no_key" ON "CREDIT_CARD_INSTALLMENT"("plan_id", "installment_no");
CREATE INDEX "CREDIT_CARD_INSTALLMENT_statement_date_idx" ON "CREDIT_CARD_INSTALLMENT"("statement_date");
CREATE UNIQUE INDEX "CREDIT_CARD_BILLING_STATEMENT_card_cycle_end_key" ON "CREDIT_CARD_BILLING_STATEMENT"("card_wallet_id", "cycle_end_date");
CREATE INDEX "CREDIT_CARD_BILLING_STATEMENT_workspace_status_due_idx" ON "CREDIT_CARD_BILLING_STATEMENT"("workspace_id", "status", "due_date");
CREATE UNIQUE INDEX "CREDIT_CARD_BILLING_STATEMENT_ITEM_unique" ON "CREDIT_CARD_BILLING_STATEMENT_ITEM"("statement_id", "obligation_entry_id", "installment_id") NULLS NOT DISTINCT;
CREATE INDEX "CREDIT_CARD_BILLING_STATEMENT_ITEM_obligation_idx" ON "CREDIT_CARD_BILLING_STATEMENT_ITEM"("obligation_entry_id");
CREATE INDEX "CREDIT_CARD_BILLING_STATEMENT_ITEM_installment_idx" ON "CREDIT_CARD_BILLING_STATEMENT_ITEM"("installment_id");
CREATE INDEX "CREDIT_CARD_BILLING_STATEMENT_ITEM_wallet_idx" ON "CREDIT_CARD_BILLING_STATEMENT_ITEM"("funding_wallet_id");
CREATE INDEX "TRANSACTION_billing_statement_id_idx" ON "TRANSACTION"("billing_statement_id");

ALTER TABLE "CREDIT_CARD_EQUAL_INSTALLMENT_PLAN" ADD CONSTRAINT "CC_EQUAL_PLAN_workspace_fkey" FOREIGN KEY ("workspace_id") REFERENCES "WORKSPACES"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "CREDIT_CARD_EQUAL_INSTALLMENT_PLAN" ADD CONSTRAINT "CC_EQUAL_PLAN_card_fkey" FOREIGN KEY ("card_wallet_id") REFERENCES "CREDIT_CARD_PROFILE"("wallet_id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "CREDIT_CARD_EQUAL_INSTALLMENT_PLAN" ADD CONSTRAINT "CC_EQUAL_PLAN_transaction_fkey" FOREIGN KEY ("transaction_id") REFERENCES "TRANSACTION"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "CREDIT_CARD_EQUAL_INSTALLMENT_PLAN" ADD CONSTRAINT "CC_EQUAL_PLAN_fee_transaction_fkey" FOREIGN KEY ("fee_transaction_id") REFERENCES "TRANSACTION"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "CREDIT_CARD_EQUAL_INSTALLMENT_PLAN" ADD CONSTRAINT "CC_EQUAL_PLAN_member_fkey" FOREIGN KEY ("created_by_member_id") REFERENCES "WORKSPACE_MEMBERS"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "CREDIT_CARD_INSTALLMENT" ADD CONSTRAINT "CC_INSTALLMENT_equal_plan_fkey" FOREIGN KEY ("plan_id") REFERENCES "CREDIT_CARD_EQUAL_INSTALLMENT_PLAN"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "CREDIT_CARD_BILLING_STATEMENT" ADD CONSTRAINT "CC_BILLING_STATEMENT_workspace_fkey" FOREIGN KEY ("workspace_id") REFERENCES "WORKSPACES"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "CREDIT_CARD_BILLING_STATEMENT" ADD CONSTRAINT "CC_BILLING_STATEMENT_card_fkey" FOREIGN KEY ("card_wallet_id") REFERENCES "CREDIT_CARD_PROFILE"("wallet_id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "CREDIT_CARD_BILLING_STATEMENT_ITEM" ADD CONSTRAINT "CC_BILLING_ITEM_statement_fkey" FOREIGN KEY ("statement_id") REFERENCES "CREDIT_CARD_BILLING_STATEMENT"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "CREDIT_CARD_BILLING_STATEMENT_ITEM" ADD CONSTRAINT "CC_BILLING_ITEM_obligation_fkey" FOREIGN KEY ("obligation_entry_id") REFERENCES "CREDIT_CARD_OBLIGATION_ENTRY"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "CREDIT_CARD_BILLING_STATEMENT_ITEM" ADD CONSTRAINT "CC_BILLING_ITEM_installment_fkey" FOREIGN KEY ("installment_id") REFERENCES "CREDIT_CARD_INSTALLMENT"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "TRANSACTION" ADD CONSTRAINT "TRANSACTION_billing_statement_id_fkey" FOREIGN KEY ("billing_statement_id") REFERENCES "CREDIT_CARD_BILLING_STATEMENT"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

INSERT INTO "CATEGORY" ("id", "workspace_id", "name", "code", "color", "type", "icon", "jar_code", "order", "status", "created_at", "updated_at")
SELECT gen_random_uuid(), w.id, 'Phí tài chính', 'EXPENSE_INSTALLMENT_FEE', '#64748B', 'expense', 'card', 'RESPONSIBILITY', 105, 'active', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
FROM "WORKSPACES" w
ON CONFLICT ("workspace_id", "code") DO NOTHING;
