ALTER TABLE "RECURRING_TRANSACTION"
ADD COLUMN "start_date" DATE,
ADD COLUMN "end_date" DATE,
ADD COLUMN "completed_at" TIMESTAMPTZ(6);

UPDATE "RECURRING_TRANSACTION"
SET "start_date" = "created_at"::date;

ALTER TABLE "RECURRING_TRANSACTION"
ALTER COLUMN "start_date" SET NOT NULL;

ALTER TABLE "RECURRING_TRANSACTION"
ADD CONSTRAINT "RECURRING_TRANSACTION_effective_dates_check"
CHECK ("end_date" IS NULL OR "end_date" >= "start_date");
