CREATE TABLE "RECURRING_TRANSACTION" (
    "id" UUID NOT NULL,
    "workspace_id" UUID NOT NULL,
    "created_by_member_id" UUID NOT NULL,
    "wallet_id" UUID NOT NULL,
    "to_wallet_id" UUID,
    "category_id" UUID,
    "type" "TRANSACTION_TYPE" NOT NULL,
    "amount" DECIMAL(20,4) NOT NULL,
    "description" TEXT,
    "day_of_month" INTEGER NOT NULL,
    "next_execution_date" DATE NOT NULL,
    "status" "STATUS" NOT NULL DEFAULT 'active',
    "last_error" TEXT,
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ(6) NOT NULL,
    "deleted_at" TIMESTAMPTZ(6),

    CONSTRAINT "RECURRING_TRANSACTION_pkey" PRIMARY KEY ("id"),
    CONSTRAINT "RECURRING_TRANSACTION_day_of_month_check" CHECK ("day_of_month" BETWEEN 1 AND 31)
);

ALTER TABLE "TRANSACTION"
ADD COLUMN "recurring_transaction_id" UUID,
ADD COLUMN "recurring_period" VARCHAR(7);

CREATE INDEX "RECURRING_TRANSACTION_workspace_id_status_next_execution_date_idx"
ON "RECURRING_TRANSACTION"("workspace_id", "status", "next_execution_date");

CREATE INDEX "RECURRING_TRANSACTION_wallet_id_idx"
ON "RECURRING_TRANSACTION"("wallet_id");

CREATE INDEX "RECURRING_TRANSACTION_to_wallet_id_idx"
ON "RECURRING_TRANSACTION"("to_wallet_id");

CREATE INDEX "RECURRING_TRANSACTION_category_id_idx"
ON "RECURRING_TRANSACTION"("category_id");

CREATE UNIQUE INDEX "TRANSACTION_recurring_transaction_id_recurring_period_key"
ON "TRANSACTION"("recurring_transaction_id", "recurring_period");

ALTER TABLE "RECURRING_TRANSACTION"
ADD CONSTRAINT "RECURRING_TRANSACTION_workspace_id_fkey"
FOREIGN KEY ("workspace_id") REFERENCES "WORKSPACES"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

ALTER TABLE "RECURRING_TRANSACTION"
ADD CONSTRAINT "RECURRING_TRANSACTION_created_by_member_id_fkey"
FOREIGN KEY ("created_by_member_id") REFERENCES "WORKSPACE_MEMBERS"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

ALTER TABLE "RECURRING_TRANSACTION"
ADD CONSTRAINT "RECURRING_TRANSACTION_wallet_id_fkey"
FOREIGN KEY ("wallet_id") REFERENCES "WALLETS"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

ALTER TABLE "RECURRING_TRANSACTION"
ADD CONSTRAINT "RECURRING_TRANSACTION_to_wallet_id_fkey"
FOREIGN KEY ("to_wallet_id") REFERENCES "WALLETS"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

ALTER TABLE "RECURRING_TRANSACTION"
ADD CONSTRAINT "RECURRING_TRANSACTION_category_id_fkey"
FOREIGN KEY ("category_id") REFERENCES "CATEGORY"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

ALTER TABLE "TRANSACTION"
ADD CONSTRAINT "TRANSACTION_recurring_transaction_id_fkey"
FOREIGN KEY ("recurring_transaction_id") REFERENCES "RECURRING_TRANSACTION"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
