"use client";
import { useMemo, useState, useTransition } from "react";
import { addTransactionAction, addWalletAction, approveTransactionAction, deleteTransactionsAction } from "@/app/dashboard/actions";
import { Download, Plus, Search, Trash2, WalletCards } from "lucide-react";
type Option = { id: string; name: string; color?: string };
type LedgerItem = { id: string; amount: string; type: "income" | "expense" | "transfer"; status: "pending" | "scheduled" | "approved" | "rejected"; description: string | null; date: string; wallet: string; category: { name: string; color: string } | null; member: string };
export function DashboardActions({ wallets, categories, canManageWallets }: { wallets: Option[]; categories: Option[]; canManageWallets: boolean }) {
 const [open,setOpen]=useState<"wallet"|"transaction"|null>(null); const [message,setMessage]=useState<string|null>(null); const [pending,start]=useTransition();
 function wallet(data:FormData){start(async()=>{const r=await addWalletAction({name:data.get("name"),openingBalance:data.get("openingBalance"),description:data.get("description")||undefined});setMessage(r.ok?"Đã tạo ví.":r.message??"Có lỗi.");if(r.ok)setOpen(null);});}
 function transaction(data:FormData){start(async()=>{const r=await addTransactionAction({walletId:data.get("walletId"),toWalletId:data.get("toWalletId")||undefined,categoryId:data.get("categoryId")||undefined,type:data.get("type"),amount:data.get("amount"),description:data.get("description")||undefined,date:data.get("date")});setMessage(r.ok?"Đã gửi giao dịch để xác nhận.":r.message??"Có lỗi.");if(r.ok)setOpen(null);});}
 return <><div className="flex gap-2"><button disabled={!canManageWallets} aria-label="Thêm ví" title={canManageWallets?"Thêm ví":"Chỉ Admin được quản lý ví"} onClick={()=>setOpen("wallet")} className="button-secondary icon-button"><WalletCards size={18}/></button><button aria-label="Thêm giao dịch" title="Thêm giao dịch" onClick={()=>setOpen("transaction")} className="button-primary icon-button"><Plus size={19}/></button></div>{!canManageWallets&&<p className="mt-2 text-right text-xs text-slate-500">Chỉ Admin được quản lý ví.</p>}{message&&<p className="mt-2 text-right text-sm" role="status">{message}</p>}{open&&<div className="fixed inset-0 z-50 grid place-items-center bg-[var(--overlay)] p-4"><form action={open==="wallet"?wallet:transaction} className="sunrise-card w-full max-w-md space-y-3 p-6"><h2 className="text-xl font-semibold">{open==="wallet"?"Thêm ví":"Thêm giao dịch"}</h2>{open==="wallet"?<><Field name="name" label="Tên ví" /><Field name="openingBalance" label="Số dư đầu kỳ" inputMode="decimal" /><Field name="description" label="Ghi chú" required={false} /></>:<><select required name="type" className="field"><option value="expense">Chi tiêu</option><option value="income">Thu nhập</option><option value="transfer">Chuyển khoản</option></select><select required name="walletId" className="field"><option value="">Chọn ví</option>{wallets.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select><select name="toWalletId" className="field"><option value="">Ví nhận (chỉ dùng khi chuyển khoản)</option>{wallets.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select><select name="categoryId" className="field"><option value="">Chọn danh mục</option>{categories.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select><Field name="amount" label="Số tiền" inputMode="decimal" /><input required name="date" type="date" className="field" defaultValue={new Date().toISOString().slice(0,10)} /><Field name="description" label="Nội dung" required={false} /></>}<div className="flex justify-end gap-2"><button type="button" onClick={()=>setOpen(null)} className="button-secondary">Hủy</button><button disabled={pending} className="button-primary">{pending?"Đang lưu":"Lưu"}</button></div></form></div>}</>;
}
function Field({name,label,required=true,inputMode}:{name:string;label:string;required?:boolean;inputMode?:"decimal"}){return <input required={required} name={name} inputMode={inputMode} placeholder={label} className="field"/>}
export function Ledger({ transactions, canApprove, monthLabel, wallets, categories, canManageWallets, readonly = false }: { transactions: LedgerItem[]; canApprove: boolean; monthLabel: string; wallets: Option[]; categories: Option[]; canManageWallets: boolean; readonly?: boolean }) {
 const [query,setQuery]=useState(""); const [status,setStatus]=useState("all"); const [selected,setSelected]=useState<Set<string>>(new Set()); const [busy,start]=useTransition();
 const rows=useMemo(()=>transactions.filter(x=>(status==="all"||x.status===status)&&`${x.description??""} ${x.category?.name??""} ${x.wallet} ${x.member}`.toLocaleLowerCase().includes(query.toLocaleLowerCase())),[transactions,query,status]);
 function exportCsv(){const csv=["Ngày,Loại,Danh mục,Ví,Số tiền,Trạng thái,Ghi chú",...rows.map(x=>[new Date(x.date).toLocaleDateString("vi-VN"),x.type,x.category?.name??"",x.wallet,x.amount,x.status,x.description??""].map(v=>`"${String(v).replaceAll('"','""')}"`).join(","))].join("\n");const a=document.createElement("a");a.href=URL.createObjectURL(new Blob(["\ufeff"+csv],{type:"text/csv;charset=utf-8"}));a.download="so-thu-chi.csv";a.click();URL.revokeObjectURL(a.href);}
 const allSelected=rows.length>0&&rows.every(row=>selected.has(row.id));
 function toggle(id:string){setSelected(current=>{const next=new Set(current);if(next.has(id))next.delete(id);else next.add(id);return next;});}
 function toggleAll(){setSelected(current=>{const next=new Set(current);if(allSelected)rows.forEach(row=>next.delete(row.id));else rows.forEach(row=>next.add(row.id));return next;});}
 function remove(){const ids=[...selected];if(!ids.length||!window.confirm(`Xóa ${ids.length} giao dịch đã chọn? Giao dịch đã ghi nhận sẽ được hoàn tác số dư ví.`))return;start(async()=>{const result=await deleteTransactionsAction(ids);if(result.ok)setSelected(new Set());});}
 return <div className="ledger-shell"><div className="ledger-toolbar"><label className="ledger-search"><Search size={16}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Tìm giao dịch" aria-label="Tìm giao dịch hoặc ghi chú"/></label><select value={status} onChange={e=>setStatus(e.target.value)} className="ledger-status" aria-label="Lọc trạng thái"><option value="all">Tất cả</option><option value="approved">Đã ghi nhận</option><option value="pending">Chờ xác nhận</option><option value="rejected">Đã từ chối</option></select><button className="button-secondary icon-button" onClick={exportCsv} title="Xuất CSV" aria-label="Xuất CSV"><Download size={16}/></button>{canApprove&&<button className="button-secondary icon-button text-red-600" disabled={!selected.size||busy} onClick={remove} title={selected.size?`Xóa ${selected.size} giao dịch đã chọn`:"Chọn giao dịch để xóa"} aria-label="Xóa giao dịch đã chọn"><Trash2 size={16}/></button>}{!readonly&&<DashboardActions wallets={wallets} categories={categories} canManageWallets={canManageWallets}/>}</div><div className="ledger-scroll-area"><table className="w-full min-w-[760px] text-left text-sm"><thead><tr className="border-b border-[#ece4da] text-xs uppercase tracking-wide text-slate-500">{canApprove&&<th className="w-10"><input type="checkbox" checked={allSelected} onChange={toggleAll} aria-label="Chọn tất cả giao dịch đang hiển thị"/></th>}<th>Giao dịch</th><th>Danh mục</th><th>Ví</th><th>Ngày</th><th className="text-right">Số tiền</th><th>Trạng thái</th><th></th></tr></thead><tbody>{rows.map((x,index)=><tr key={x.id} className="border-b border-[#f1e9e0]">{canApprove&&<td><input type="checkbox" checked={selected.has(x.id)} onChange={()=>toggle(x.id)} aria-label={`Chọn giao dịch ${x.description||x.id}`}/></td>}<td><p className="font-medium">{x.description||"Không có nội dung"}</p><p className="mt-1 text-xs text-slate-500">#{String(transactions.length-index).padStart(5,"0")} · {x.member}</p></td><td>{x.category?<span className="category-tag" style={{backgroundColor:`${x.category.color}22`,color:x.category.color}}>{x.category.name}</span>:"—"}</td><td>{x.wallet}</td><td>{new Date(x.date).toLocaleDateString("vi-VN")}</td><td className={`text-right font-semibold ${x.type==="income"?"text-[#168a39]":x.type==="expense"?"text-[#e84335]":"text-[#17233c]"}`}>{x.type==="income"?"+":x.type==="expense"?"−":"↔"}{new Intl.NumberFormat("vi-VN").format(Number(x.amount))} ₫</td><td><Status value={x.status}/></td><td>{canApprove&&x.status==="pending"&&<button disabled={busy} onClick={()=>start(async()=>{await approveTransactionAction(x.id);})} className="button-secondary text-xs">Duyệt</button>}</td></tr>)}{rows.length===0&&<tr><td colSpan={canApprove?8:7} className="p-10 text-center text-slate-500">Chưa có giao dịch phù hợp.</td></tr>}</tbody></table></div><p className="ledger-record-count">Hiển thị {rows.length} giao dịch trong {monthLabel}.</p></div>;
}
function Status({value}:{value:LedgerItem["status"]}){const label={approved:"Đã ghi nhận",pending:"Chờ xác nhận",scheduled:"Dự kiến",rejected:"Đã từ chối"}[value];return <span className={`status status-${value}`}>{label}</span>}
