import { getServerSession } from "next-auth";
import { redirect } from "next/navigation";
import Decimal from "decimal.js";
import { authOptions } from "@/auth";
import { Ledger } from "@/app/dashboard/dashboard-actions";
import { DashboardFooterNotice } from "@/app/dashboard/dashboard-footer-notice";
import { DashboardSummaryPanel } from "@/app/dashboard/dashboard-summary-panel";
import { formatAmount } from "@/lib/format";
import { prisma } from "@/lib/prisma";
import { resolveActiveWorkspaceId } from "@/services/active-workspace";
import { availableCategoryWhere } from "@/services/category-visibility";

export async function WorkspaceDashboard({ targetWorkspaceId }: { targetWorkspaceId?: string } = {}) {
  const session = await getServerSession(authOptions); if (!session?.user?.id) redirect("/sign-in");
  const workspaceId = targetWorkspaceId ?? await resolveActiveWorkspaceId(session.user.id); if (!workspaceId) return <p>Không có workspace đang hoạt động.</p>;
  const membership = await prisma.workspaceMember.findFirst({ where: { userId: session.user.id, workspaceId, status: "active", deletedAt: null, workspace: { deletedAt: null } }, include: { workspace: { include: { monthlyRecord: true } }, role: true } }); if (!membership) return <p>Không có quyền xem workspace này.</p>;
  const archived = membership.workspace.status === "deactive"; const period = membership.workspace.monthlyRecord?.period; const today = new Date(); const monthStart = period ? new Date(`${period}-01T00:00:00.000Z`) : new Date(Date.UTC(today.getUTCFullYear(), today.getUTCMonth(), 1)); const nextMonth = period ? new Date(Date.UTC(monthStart.getUTCFullYear(), monthStart.getUTCMonth() + 1, 1)) : new Date(Date.UTC(today.getUTCFullYear(), today.getUTCMonth() + 1, 1));
  const [walletLinks, categories, transactions] = await Promise.all([prisma.workspaceWallet.findMany({ where: { workspaceId, wallet: { status: "active", deletedAt: null } }, include: { wallet: true }, orderBy: { wallet: { name: "asc" } } }), prisma.category.findMany({ where: availableCategoryWhere(workspaceId), select: { id: true, name: true, color: true }, orderBy: { sortOrder: "asc" } }), prisma.transaction.findMany({ where: { deletedAt: null, date: { gte: monthStart, lt: nextMonth }, member: { workspaceId } }, include: { wallet: { select: { name: true } }, category: { select: { name: true, color: true } }, member: { include: { user: { select: { username: true } } } } }, orderBy: [{ date: "desc" }, { createdAt: "desc" }], take: 100 })]);
  const approved = transactions.filter((item) => item.workflowStatus === "approved"); const income = approved.filter((item) => item.type === "income").reduce((sum, item) => sum.plus(item.amount.toString()), new Decimal(0)); const expense = approved.filter((item) => item.type === "expense").reduce((sum, item) => sum.plus(item.amount.toString()), new Decimal(0)); const balance = walletLinks.reduce((sum, item) => sum.plus(item.wallet.currentBalance.toString()), new Decimal(0)); const monthLabel = new Intl.DateTimeFormat("vi-VN", { month: "long", year: "numeric", timeZone: "Asia/Ho_Chi_Minh" }).format(monthStart); const ledger = transactions.map((item) => ({ id: item.id, amount: item.amount.toString(), type: item.type, status: item.workflowStatus, description: item.description, date: item.date.toISOString(), wallet: item.wallet.name, category: item.category ? { name: item.category.name, color: item.category.color } : null, member: item.member.user.username }));
  const pendingCount = transactions.filter((item) => item.workflowStatus === "pending").length;
  return <div>{archived && <DashboardFooterNotice message="Workspace tháng đã khóa — chỉ xem dữ liệu, không thể thao tác."/>}<div className="dashboard-workspace-view"><div className="dashboard-ledger-column"><section className="sunrise-card dashboard-ledger-card overflow-hidden"><Ledger transactions={ledger} canApprove={membership.role.code === "ADMIN" && !archived} monthLabel={monthLabel} wallets={walletLinks.map(({ wallet }) => ({ id: wallet.id, name: wallet.name }))} categories={categories} canManageWallets={membership.role.code === "ADMIN" && !archived} readonly={archived}/></section></div><DashboardSummaryPanel metrics={[{ label: "Tổng số dư", value: `${formatAmount(balance)} ₫`, note: `${walletLinks.length} ví đang hoạt động`, tone: "balance" }, { label: "Thu nhập", value: `${formatAmount(income)} ₫`, note: "Đã ghi nhận", tone: "income" }, { label: "Chi tiêu", value: `${formatAmount(expense)} ₫`, note: "Đã ghi nhận", tone: "expense" }, { label: "Chờ xác nhận", value: `${pendingCount} giao dịch`, note: "Chưa thay đổi số dư", tone: "pending" }]} wallets={walletLinks.map(({ wallet }) => ({ id: wallet.id, name: wallet.name, balance: `${formatAmount(wallet.currentBalance.toString())} ₫` }))}/></div></div>;
}
export default WorkspaceDashboard;
