"use client";

import Decimal from "decimal.js";
import { ChevronDown, CircleAlert, Funnel, RefreshCw, TrendingDown, TrendingUp, WalletCards } from "lucide-react";
import { useState } from "react";
import { formatAmount } from "@/lib/format";

type Transaction = { id: string; amount: string; type: "income" | "expense" | "transfer"; status: "pending" | "scheduled" | "approved" | "rejected"; description: string | null; date: string; walletId: string; wallet: string; categoryId: string | null; category: { name: string; color: string } | null; memberId: string; member: string };
type Props = { workspace: { id: string; name: string; currency: string }; wallets: { id: string; name: string; balance: string; updatedAt: string }[]; totalByCurrency: Record<string, string>; categories: { id: string; name: string; color: string }[]; members: { id: string; name: string }[]; transactions: Transaction[]; monthlyExpenses: { period: string; amount: string }[] };
const money = (value: Decimal.Value, currency: string) => `${formatAmount(value)} ${currency}`;
const statusLabel = { approved: "Đã ghi nhận", pending: "Chờ duyệt", scheduled: "Đã lên lịch", rejected: "Đã từ chối" };

export function OverviewDashboard({ workspace, wallets, totalByCurrency, categories, members, transactions, monthlyExpenses }: Props) {
  const now = new Date(); const initialMonth = `${now.getFullYear()}-${String(now.getMonth() + 1).padStart(2, "0")}`;
  const [month, setMonth] = useState(initialMonth); const [walletId, setWalletId] = useState("all"); const [categoryId, setCategoryId] = useState("all"); const [memberId, setMemberId] = useState("all"); const [type, setType] = useState("all"); const [showPending, setShowPending] = useState(false);
  const filtered = transactions.filter((item) => item.date.slice(0, 7) === month && (walletId === "all" || item.walletId === walletId) && (categoryId === "all" || item.categoryId === categoryId) && (memberId === "all" || item.memberId === memberId) && (type === "all" || item.type === type));
  const posted = filtered.filter((item) => item.status === "approved");
  const totals = posted.reduce((result, item) => ({ income: item.type === "income" ? result.income.plus(item.amount) : result.income, expense: item.type === "expense" ? result.expense.plus(item.amount) : result.expense }), { income: new Decimal(0), expense: new Decimal(0) });
  const expenseByCategory = (() => {
    const rows = new Map<string, { name: string; color: string; amount: Decimal }>();
    posted.filter((item) => item.type === "expense").forEach((item) => { const key = item.categoryId ?? "uncategorized"; const prior = rows.get(key); rows.set(key, { name: item.category?.name ?? "Chưa phân loại", color: item.category?.color ?? "var(--chart-7)", amount: (prior?.amount ?? new Decimal(0)).plus(item.amount) }); });
    return [...rows.values()].sort((a, b) => b.amount.comparedTo(a.amount));
  })();
  const pending = filtered.filter((item) => item.status === "pending");
  const reset = () => { setMonth(initialMonth); setWalletId("all"); setCategoryId("all"); setMemberId("all"); setType("all"); setShowPending(false); };

  return <div className="overview-shell">
    <div className="overview-title"><div><p>Workspace · {workspace.name}</p><h1>Tổng quan tài chính</h1></div><a className="button-primary overview-add" href={`/workspace/${workspace.id}`} aria-label="Thêm giao dịch">Thêm giao dịch</a></div>
    <section className="overview-filters" aria-label="Bộ lọc dashboard"><Funnel size={17}/><label>Tháng<input type="month" value={month} onChange={(event) => setMonth(event.target.value)} /></label><Select value={walletId} setValue={setWalletId} label="Tất cả ví" options={wallets.map((item) => ({ value: item.id, label: item.name }))} /><Select value={categoryId} setValue={setCategoryId} label="Tất cả hạng mục" options={categories.map((item) => ({ value: item.id, label: item.name }))} /><Select value={type} setValue={setType} label="Tất cả loại" options={[{ value: "income", label: "Thu nhập" }, { value: "expense", label: "Chi phí" }, { value: "transfer", label: "Chuyển khoản" }]} /><Select value={memberId} setValue={setMemberId} label="Tất cả thành viên" options={members.map((item) => ({ value: item.id, label: item.name }))} /><button onClick={reset} className="overview-reset"><RefreshCw size={15}/> Đặt lại</button></section>
    <div className="overview-kpis"><Metric title="Tổng số dư ví" value={Object.entries(totalByCurrency).map(([currency, total]) => money(total, currency)).join(" · ")} note={`${wallets.length} ví đang hoạt động`} icon={<WalletCards size={18}/>} tone="primary"/><Metric title="Thu nhập trong kỳ" value={money(totals.income, workspace.currency)} note="Chỉ giao dịch đã ghi nhận" icon={<TrendingUp size={18}/>} tone="income"/><Metric title="Chi phí trong kỳ" value={money(totals.expense, workspace.currency)} note="Chỉ giao dịch đã ghi nhận" icon={<TrendingDown size={18}/>} tone="expense"/><Metric title="Dòng tiền ròng" value={money(totals.income.minus(totals.expense), workspace.currency)} note="Thu nhập trừ chi phí" icon={<TrendingUp size={18}/>} tone="primary"/></div>
    <div className="overview-grid"><MonthlyExpenseChart expenses={monthlyExpenses} currency={workspace.currency}/>
      <section className="overview-card overview-category"><header><div><h2>Chi phí theo hạng mục</h2><p>Chỉ tính giao dịch đã ghi nhận</p></div></header>{expenseByCategory.length ? <div className="category-list">{expenseByCategory.map((item) => <div className="category-row" key={item.name}><span className="category-dot" style={{ background: item.color }}/><div><strong>{item.name}</strong><div className="category-track"><span style={{ width: `${item.amount.div(totals.expense).times(100)}%`, background: item.color }}/></div></div><b>{item.amount.div(totals.expense).times(100).toFixed(0)}%</b><small>{money(item.amount, workspace.currency)}</small></div>)}</div> : <Empty text="Chưa có chi phí đã ghi nhận để phân bổ." />}</section>
      <section className="overview-card overview-wallets"><header><div><h2>Ví trong workspace</h2><p>Số dư hiện tại theo dữ liệu ví</p></div></header>{wallets.length ? <div className="wallet-list">{wallets.map((wallet) => <article key={wallet.id}><span><WalletCards size={17}/></span><div><strong>{wallet.name}</strong><small>Cập nhật {new Intl.DateTimeFormat("vi-VN", { dateStyle: "short" }).format(new Date(wallet.updatedAt))}</small></div><b>{money(wallet.balance, workspace.currency)}</b></article>)}</div> : <Empty text="Workspace này chưa có ví đang hoạt động." />}</section>
      <section className="overview-card overview-recent"><header><div><h2>Giao dịch gần đây</h2><p>Được sắp xếp theo ngày mới nhất</p></div><a href={`/workspace/${workspace.id}`}>Xem tất cả</a></header><div className="recent-table">{filtered.slice(0, 6).map((item) => <article key={item.id}><div><strong title={item.description ?? "Không có nội dung"}>{item.description ?? "Không có nội dung"}</strong><small>{item.category?.name ?? "Chưa phân loại"} · {item.wallet} · {item.member}</small></div><time>{new Intl.DateTimeFormat("vi-VN", { day: "2-digit", month: "2-digit" }).format(new Date(item.date))}</time><b className={item.type}>{item.type === "income" ? "+" : item.type === "expense" ? "−" : "↔"}{money(item.amount, workspace.currency)}</b><span className={`overview-status ${item.status}`}>{statusLabel[item.status]}</span></article>)}{!filtered.length && <Empty text="Không có giao dịch phù hợp với bộ lọc." />}</div></section>
      <section className="overview-card overview-pending"><header><div><h2>Cần xử lý</h2><p>Giao dịch đang chờ duyệt</p></div><button onClick={() => setShowPending(!showPending)} aria-expanded={showPending}><ChevronDown size={17}/></button></header><div className={showPending ? "pending-list open" : "pending-list"}>{pending.length ? pending.map((item) => <article key={item.id}><CircleAlert size={17}/><div><strong>{item.description ?? "Không có nội dung"}</strong><small>{item.member} · {money(item.amount, workspace.currency)}</small></div></article>) : <Empty text="Không có giao dịch nào cần xử lý." />}</div><p className="pending-summary">{pending.length} giao dịch đang chờ duyệt</p></section>
    </div>
  </div>;
}
function MonthlyExpenseChart({ expenses, currency }: { expenses: { period: string; amount: string }[]; currency: string }) {
  const [range, setRange] = useState<3 | 6 | 12>(3);
  const rows = expenses.slice(-range).map((item) => ({ ...item, value: new Decimal(item.amount) }));
  const peak = Decimal.max(1, ...rows.map((item) => item.value));
  const points = rows.map((item, index) => {
    const x = rows.length === 1 ? 50 : 8 + (index * 84) / (rows.length - 1);
    const y = new Decimal(92).minus(item.value.div(peak).times(78)).toNumber();
    return `${x},${y}`;
  }).join(" ");
  return <section className="overview-card overview-flow"><header><div><h2>Chi tiêu theo tháng</h2><p>Chỉ tính khoản chi đã ghi nhận của các workspace theo tháng.</p></div><div className="expense-range" aria-label="Khoảng thời gian biểu đồ">{([3, 6, 12] as const).map((value) => <button type="button" key={value} onClick={() => setRange(value)} className={range === value ? "active" : ""}>{value} tháng</button>)}</div></header><div className="monthly-expense-chart" aria-label={`Biểu đồ chi tiêu ${range} tháng gần nhất`}><div className="monthly-scale"><span>{money(peak, currency)}</span><span>0</span></div><div className="monthly-plot"><svg viewBox="0 0 100 100" preserveAspectRatio="none" aria-hidden="true"><polyline points={points} /></svg><div className="monthly-columns">{rows.map((item) => { const percent = item.value.div(peak).times(100).toNumber(); const [year, month] = item.period.split("-"); return <div className="monthly-column" key={item.period} title={`${month}/${year}: ${money(item.value, currency)}`}><span className="monthly-bar" style={{ height: `${percent}%` }}/><i style={{ bottom: `${percent}%` }}/><small>{month}/{year.slice(2)}</small></div>; })}</div></div></div></section>;
}
function Select({ value, setValue, label, options }: { value: string; setValue: (value: string) => void; label: string; options: { value: string; label: string }[] }) { return <label><select value={value} onChange={(event) => setValue(event.target.value)} aria-label={label}><option value="all">{label}</option>{options.map((option) => <option key={option.value} value={option.value}>{option.label}</option>)}</select></label>; }
function Metric({ title, value, note, icon, tone }: { title: string; value: string; note: string; icon: React.ReactNode; tone: string }) { return <section className={`overview-metric ${tone}`}><span>{icon}</span><p>{title}</p><strong>{value}</strong><small>{note}</small></section>; }
function Empty({ text }: { text: string }) { return <div className="overview-empty">{text}</div>; }
